version: "3.9"

services:
   api:
      build:
         context: .
         dockerfile: ./apps/api/Dockerfile
      env_file:
         - ./apps/api/.env
      environment:
         DATABASE_URL: postgres://romanshevchuk:admin@postgres:5432/rooms-docker?schema=public
      depends_on:
         postgres:
            condition: service_healthy
      restart: always
      ports:
         - "4000:4000"

   postgres:
      image: postgres:16
      environment:
         POSTGRES_DB: rooms-docker
         POSTGRES_USER: romanshevchuk
         POSTGRES_PASSWORD: admin
      healthcheck:
         test: ["CMD-SHELL", "pg_isready -U romanshevchuk -d rooms-docker"]
         interval: 5s
         timeout: 5s
         retries: 20
      ports:
         - "5432:5432"
      volumes:
         - pgdata:/var/lib/postgresql/data
      restart: always

volumes:
   pgdata:
